# Generated by Django 6.0.5 on 2026-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approved'), ('reject', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='delay_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='hrd_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_valid_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='npwp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('leave', 'Leave'), ('overtime', 'Overtime')], default='present', max_length=20),
        ),
    ]
