# Generated by Django 6.0.5 on 2026-06-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_attendance_options_alter_leave_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('npwp', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('shift', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('job_position', models.CharField(blank=True, max_length=100)),
                ('job_level', models.CharField(blank=True, max_length=100)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('employee_status', models.CharField(blank=True, max_length=50)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status_employee', models.CharField(blank=True, max_length=50)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, max_length=30)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('hrd', 'HRD'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee',
            field=models.OneToOneField(blank=True, help_text='Tautkan ke baris Employee jika role = employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='employee.employee'),
        ),
    ]
