# Generated by Django 6.0.5 on 2026-06-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_alter_profile_role_profile_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('late_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Draft', 'Draft'), ('Waiting Supervisor', 'Waiting Supervisor'), ('Supervisor Approved', 'Supervisor Approved'), ('Supervisor Rejected', 'Supervisor Rejected'), ('Approved', 'Approved'), ('Reject', 'Reject'), ('Done', 'Done')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'db_table': 'payroll',
                'ordering': ['-period_end', 'employee__full_name'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='delay_minutes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='hrd_notes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_valid_location',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('leave', 'Leave')], default='present', max_length=20),
        ),
    ]
