# Generated by Django 6.0.4 on 2026-07-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_options_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_descriptor',
            field=models.TextField(blank=True, help_text='128-dimensi face descriptor (JSON array) dari face-api.js — dipakai untuk verifikasi wajah saat absen', null=True),
        ),
    ]
