# Generated by Django 6.0.5 on 2026-07-16 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_profile_face_descriptor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(help_text="Contoh: 'Idul Fitri', 'Hari Kemerdekaan'", max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('hrd', 'HRD'), ('supervisor', 'Supervisor'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('supervisor', 'Supervisor (Atasan)'), ('hrd', 'HRD')], max_length=20)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='employee.payroll')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Approval',
                'verbose_name_plural': 'Payroll Approvals',
                'ordering': ['payroll_id', 'level'],
                'unique_together': {('payroll', 'level')},
            },
        ),
    ]
